---

- name: Ensure snapd is installed
  become: yes
  package:
    name: snapd
    state: present
  when: ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu"

- name: Enable snapd service
  become: yes
  service:
    name: snapd
    state: started
    enabled: yes
  when: not skipservices and (ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu")

- name: Create /snap for classic snap support
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: ansible_facts["os_family"] == "RedHat"
