---
development_packages:
  - build-essential
  - autoconf
  - automake
  - curl
  - entr
  - ethtool
  - git
  - git-doc
  - imagemagick
  - inotify-tools
  - jq
  - libffi-dev
  - libgl1-mesa-dev
  - libglu1-mesa-dev
  - libmagickwand-dev
  - libncurses5-dev
  - libpng-dev
  - libpq-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libtool
  - libwxgtk3.0-gtk3-dev
  - libxslt-dev
  - libyaml-dev
  - nmap
  - optipng
  - pwgen
  - tree
  - ruby-dev
  - shellcheck
  - ripgrep
  - sqlite3
  - tmux
  - unixodbc-dev
  - whois
  - postgresql-client
  - rclone
  - dstat
  - htop
  - strace
  - gawk
  - zsh

java_package: default-jdk

neovim_dependencies:
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf
  - automake
  - cmake
  - g++
  - pkg-config
  - unzip
  - curl
  - doxygen

python_packages:
  - python3
  - python3-dev
  - python3-pip

redis_package: redis-server
