---
- name: Install 1Password on Linux
  become: "{{ elevate_for_package_installation }}"
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - 1password
    - packages
  block:
    - name: Add 1Password repository
      ansible.builtin.yum_repository:
        name: 1password
        description: 1Password
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        enabled: true
        gpgcheck: true
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc

    - name: Install 1Password
      ansible.builtin.package:
        name:
          - 1password
          - 1password-cli
        state: present

- name: Install 1Password
  community.general.homebrew_cask:
    name:
      - 1password
      - 1password-cli
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - 1password
    - packages
