---
- name: Install 1Password
  become: "{{ elevate_for_flatpak_installation }}"
  community.general.flatpak:
    name: "https://downloads.1password.com/linux/flatpak/1Password.flatpakref"
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - 1password
    - packages

- name: Install 1Password
  community.general.homebrew_cask:
    name: 1password
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - 1password
    - packages
