---

# TODO: figure out Linux installation. Right now (2024-12-27) there isn't a
# Fedora package easily available and I don't have any desktop Linux around to
# figure out something more complex.

- name: Install Ghostty
  community.general.homebrew_cask:
    name: ghostty
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - ghostty
    - packages
