---

- name: Add keybase repo key
  become: yes
  rpm_key:
    key: https://keybase.io/docs/server_security/code_signing_key.asc
  when: ansible_facts["os_family"] != "Darwin"

- name: Install Keybase
  become: yes
  zypper:
    name: https://prerelease.keybase.io/keybase_amd64.rpm
    state: present
  when: ansible_facts["os_family"] != "Darwin"

- name: Install Keybase
  homebrew_cask:
    name: keybase
    state: present
  when: ansible_facts["os_family"] == "Darwin"
