---

- name: Add Keybase repo
  become: yes
  yum_repository:
    name: keybase
    description: Keybase
    baseurl: https://prerelease.keybase.io/rpm/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Keybase
  become: yes
  dnf:
    name: keybase
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Keybase
  homebrew_cask:
    name: keybase
    state: present
  when: ansible_facts["os_family"] == "Darwin"
