---
- name: Add Keybase repo
  become: true
  ansible.builtin.yum_repository:
    name: keybase
    description: Keybase
    baseurl: https://prerelease.keybase.io/rpm/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - keybase
    - packages

- name: Install Keybase
  become: true
  ansible.builtin.package:
    name: keybase
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - keybase
    - packages

- name: Install Keybase
  community.general.homebrew_cask:
    name: keybase
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - keybase
    - packages
