---
- name: Install kitty
  become: true
  ansible.builtin.dnf:
    name: kitty
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install kitty
  become: true
  ansible.builtin.apt:
    name: kitty
    state: present
  when: ansible_facts["os_family"] == "Debian"
