---

- name: Install Kitty
  homebrew_cask:
    name: kitty
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- name: Install kitty
  become: true
  package:
    name: kitty
    state: present
  when: ansible_facts["os_family"] != "Darwin"
