---

- name: Install workstation apps and tools
  become: true
  package:
    name:
      - ffmpeg
      - gimp
      - gnome-tweaks
      - mpv
      - powertop
      - virt-manager
      - virt-viewer
      - youtube-dl
      - fuse-exfat
      - mozilla-fira-mono-fonts
      - dbus-tools
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Enable Homebrew fonts cask
  homebrew_tap:
    name: Homebrew/homebrew-cask-fonts
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation GUI apps and related dependencies
  homebrew_cask:
    name:
      - firefox
      - microsoft-edge
      - font-fira-mono
      - font-fira-code
      - imageoptim
      - rectangle
      - 1password
      - dash
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation CLI tools
  homebrew:
    name:
      - ffmpeg
      - youtube-dl
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- import_tasks: iosevka.yml
- import_tasks: kitty.yml
- import_tasks: vscode.yml
- import_tasks: signal.yml
- import_tasks: keybase.yml
- import_tasks: nextcloud.yml
- import_tasks: lollypop.yml
- import_tasks: tailscale.yml
- import_tasks: gnome.yml
- import_tasks: macos.yml
