---

- name: Install dbus-tools for setting GNOME config programmatically
  become: yes
  dnf:
    name: dbus-tools
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install workstation apps and tools
  package:
    name:
      - ffmpeg
      - gimp
      - gnome-tweaks
      - mpv
      - powertop
      - virt-manager
      - virt-viewer
      - youtube-dl
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu"

- name: Install RedHat-specific workstation apps and tools
  dnf:
    name:
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - fuse-exfat
      - mozilla-fira-mono-fonts
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Ubuntu-specific workstation apps and tools
  become: yes
  apt:
    name:
      - exfat-fuse
      - fonts-firacode
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - ubuntu-restricted-extras
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Enable Homebrew fonts cask
  homebrew_tap:
    name: Homebrew/homebrew-cask-fonts
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation GUI apps and related dependencies
  homebrew_cask:
    name:
      - firefox
      - font-fira-mono
      - font-fira-code
      - font-iosevka
      - imageoptim
      - rectangle
      - sketch
      - viscosity
      - 1password
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation CLI tools
  homebrew:
    name:
      - ffmpeg
      - youtube-dl
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- import_tasks: spotify.yml
- import_tasks: signal.yml
- import_tasks: sublime.yml
- import_tasks: keybase.yml
- import_tasks: nextcloud.yml
- import_tasks: gnome.yml
- import_tasks: macos.yml
