---
- name: Include OS-specific tasks
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Install workstation apps and tools
  become: "{{ elevate_for_package_installation }}"
  ansible.builtin.package:
    name: "{{ workstation_general_packages }}"
    state: present

- ansible.builtin.import_tasks: arc.yml
- ansible.builtin.import_tasks: iosevka.yml
- ansible.builtin.import_tasks: kitty.yml
- ansible.builtin.import_tasks: sublime_text.yml
- ansible.builtin.import_tasks: signal.yml
- ansible.builtin.import_tasks: keybase.yml
- ansible.builtin.import_tasks: nextcloud.yml
- ansible.builtin.import_tasks: lollypop.yml
- ansible.builtin.import_tasks: tailscale.yml
- ansible.builtin.import_tasks: doppler.yml
- ansible.builtin.import_tasks: obsidian.yml
- ansible.builtin.import_tasks: 1password.yml

- ansible.builtin.import_tasks: gnome.yml
- ansible.builtin.import_tasks: macos.yml
