---
- name: Include OS-specific tasks
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Install workstation apps and tools
  become: "{{ elevate_for_package_installation }}"
  ansible.builtin.package:
    name: "{{ desktop_general_packages }}"
    state: present

# Cross-platform Software
- ansible.builtin.import_tasks: iosevka.yml
- ansible.builtin.import_tasks: kitty.yml
- ansible.builtin.import_tasks: signal.yml
- ansible.builtin.import_tasks: nextcloud.yml
- ansible.builtin.import_tasks: obsidian.yml
- ansible.builtin.import_tasks: 1password.yml

# Linux Apps
- ansible.builtin.import_tasks: lollypop.yml
- ansible.builtin.import_tasks: tailscale.yml

# MacOS Apps
- ansible.builtin.import_tasks: arc.yml
- ansible.builtin.import_tasks: doppler.yml

# Platform-specific config
- ansible.builtin.import_tasks: gnome.yml
- ansible.builtin.import_tasks: macos.yml
