---
- name: Include OS-specific vars
  ansible.builtin.include_vars: '{{ ansible_facts["os_family"] | lower }}.yml'

- name: Install workstation apps and tools
  become: true
  ansible.builtin.package:
    name: "{{ workstation_general_packages }}"
    state: present

- ansible.builtin.import_tasks: iosevka.yml
- ansible.builtin.import_tasks: kitty.yml
- ansible.builtin.import_tasks: vscode.yml
- ansible.builtin.import_tasks: signal.yml
- ansible.builtin.import_tasks: keybase.yml
- ansible.builtin.import_tasks: nextcloud.yml
- ansible.builtin.import_tasks: lollypop.yml
- ansible.builtin.import_tasks: tailscale.yml
- ansible.builtin.import_tasks: plexamp.yml
- ansible.builtin.import_tasks: obsidian.yml

- ansible.builtin.import_tasks: gnome.yml
- ansible.builtin.import_tasks: macos.yml
