---
- name: Include OS-specific tasks
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install workstation apps and tools
  become: "{{ elevate_for_package_installation }}"
  ansible.builtin.package:
    name: "{{ workstation_general_packages }}"
    state: present

- name: Install macOS apps
  community.general.homebrew_cask:
    name:
      - mpv
      - firefox
      - dash
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- ansible.builtin.import_tasks: iosevka.yml
- ansible.builtin.import_tasks: kitty.yml
- ansible.builtin.import_tasks: vscode.yml
- ansible.builtin.import_tasks: signal.yml
- ansible.builtin.import_tasks: keybase.yml
- ansible.builtin.import_tasks: nextcloud.yml
- ansible.builtin.import_tasks: lollypop.yml
- ansible.builtin.import_tasks: tailscale.yml
- ansible.builtin.import_tasks: plexamp.yml
- ansible.builtin.import_tasks: obsidian.yml

- ansible.builtin.import_tasks: gnome.yml
- ansible.builtin.import_tasks: macos.yml
