---

# If packages installs fail due to weird conflicts, you might have to "change
# vendor" or whatever:
#     sudo zypper dist-upgrade --from packman --allow-vendor-change
- name: Add packman repository
  become: true
  zypper_repository:
    name: packman
    repo: https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/
    priority: 90
    state: present
    auto_import_keys: true
  when: ansible_facts["os_family"] == "Suse"

- name: Install workstation apps and tools
  become: true
  package:
    name:
      - gimp
      - gnome-tweaks
      - mpv
      - powertop
      - virt-manager
      - virt-viewer
      - youtube-dl
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - fuse-exfat
      - fira-code-fonts
      - ffmpeg
      - gstreamer-plugins-good
      - gstreamer-plugins-bad
      - gstreamer-plugins-libav
      - libavcodec-full
      - vlc-codecs
    state: present
  when: ansible_facts["os_family"] == "Suse"

- name: Enable Homebrew fonts cask
  homebrew_tap:
    name: Homebrew/homebrew-cask-fonts
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation GUI apps and related dependencies
  homebrew_cask:
    name:
      - firefox
      - font-fira-mono
      - font-fira-code
      - font-computer-modern
      - imageoptim
      - rectangle
      - viscosity
      - 1password
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- name: Install workstation CLI tools
  homebrew:
    name:
      - ffmpeg
      - youtube-dl
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- import_tasks: iosevka.yml
- import_tasks: kitty.yml
- import_tasks: signal.yml
- import_tasks: keybase.yml
- import_tasks: nextcloud.yml
- import_tasks: lollypop.yml
- import_tasks: gnome.yml
- import_tasks: macos.yml
