---
- name: Install dbus-tools for setting GNOME config programmatically
  become: true
  ansible.builtin.dnf:
    name: dbus-tools
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install workstation apps and tools
  ansible.builtin.package:
    name:
      - ffmpeg
      - gimp
      - gnome-tweaks
      - mpv
      - powertop
      - virt-manager
      - virt-viewer
      - youtube-dl
    state: present
  become: true
  when: ansible_facts["os_family"] == "RedHat" or ansible_facts["distribution"] == "Ubuntu"

- name: Install RedHat-specific workstation apps and tools
  ansible.builtin.dnf:
    name:
      - fuse-exfat
      - mozilla-fira-mono-fonts
    state: present
  become: true
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Ubuntu-specific workstation apps and tools
  become: true
  ansible.builtin.apt:
    name:
      - exfat-fuse
      - fonts-firacode
      - ubuntu-restricted-extras
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- ansible.builtin.import_tasks: iosevka.yml
- ansible.builtin.import_tasks: kitty.yml
- ansible.builtin.import_tasks: vscode.yml
- ansible.builtin.import_tasks: signal.yml
- ansible.builtin.import_tasks: keybase.yml
- ansible.builtin.import_tasks: nextcloud.yml
- ansible.builtin.import_tasks: lollypop.yml
- ansible.builtin.import_tasks: tailscale.yml
- ansible.builtin.import_tasks: gnome.yml
