---

- name: Install nextcloud client
  become: true
  package:
    name: nextcloud-desktop
    state: present
  when: ansible_facts["os_family"] != "Darwin"
  tags:
  - nextcloud
  - packages

- name: Install nextcloud client
  homebrew_cask:
    name: nextcloud
    state: present
  when: ansible_facts["os_family"] == "Darwin"
