---
- name: Install Nextcloud client
  become: "{{ elevate_for_package_installation }}"
  ansible.builtin.package:
    name: nextcloud-client
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - nextcloud
    - packages

- name: Install Nextcloud client
  community.general.homebrew_cask:
    name: nextcloud
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - nextcloud
    - packages
