---

- name: Install nextcloud client
  become: yes
  apt:
    name: nextcloud-desktop
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"
  tags:
  - nextcloud
  - packages

- name: Install nextcloud client
  become: yes
  dnf:
    name: nextcloud-client
    state: present
  when: ansible_facts["distribution"] == "Fedora"
  tags:
  - nextcloud
  - packages

- name: Install nextcloud client
  homebrew_cask:
    name: nextcloud
    state: present
  when: ansible_facts["os_family"] == "Darwin"
