---

- name: Install nextcloud client
  become: true
  dnf:
    name: nextcloud-client
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - nextcloud
  - packages

- name: Install nextcloud client
  homebrew_cask:
    name: nextcloud
    state: present
  when: ansible_facts["os_family"] == "Darwin"
