---
- name: Install nextcloud client
  become: true
  ansible.builtin.dnf:
    name: nextcloud-client
    state: present
  when: ansible_facts["distribution"] == "Fedora"
  tags:
    - nextcloud
    - packages
