
---
- name: Install Obsidian
  become: true
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - obsidian
    - packages

- name: Install Obsidian
  community.general.homebrew_cask:
    name: obsidian
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - obsidian
    - packages
