---
- name: Install Plexamp
  become: true
  community.general.flatpak:
    name: com.plexamp.Plexamp
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - plexamp
    - packages

- name: Install Plexamp
  community.general.homebrew_cask:
    name: plexamp
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - plexamp
    - packages
