---
- name: Install Signal
  become: "{{ elevate_for_flatpak_installation }}"
  community.general.flatpak:
    name: org.signal.Signal
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - signal
    - packages

- name: Install Signal
  community.general.homebrew_cask:
    name: signal
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - signal
    - packages
