---
- name: Install Sublime Text on Linux
  become: "{{ elevate_for_package_installation }}"
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - packages
    - sublime_text
  block:
    - name: Install Sublime Text
      ansible.builtin.yum_repository:
        name: sublime-text
        description: Sublime Text - x86_64 - Stable
        baseurl: "https://download.sublimetext.com/rpm/stable/x86_64"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.sublimetext.com/sublimehq-rpm-pub.gpg"

    - name: Install Sublime Text
      ansible.builtin.package:
        name: sublime-text
        state: present

- name: Install Sublime Text
  community.general.homebrew_cask:
    name: sublime-text
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - packages
    - sublime_text
