---

- name: Add Tailscale repo
  become: true
  yum_repository:
    name: tailscale
    description: Tailscale
    baseurl: "https://pkgs.tailscale.com/stable/fedora/$basearch"
    enabled: true
    repo_gpgcheck: true
    gpgkey: "https://pkgs.tailscale.com/stable/fedora/repo.gpg"
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - tailscale

- name: Install Tailscale
  become: true
  package:
    name: tailscale
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - packages
  - tailscale

# On macOS Tailscale comes from the App Store
