---
- name: Add Tailscale repo
  become: true
  ansible.builtin.yum_repository:
    name: tailscale
    description: Tailscale
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    enabled: true
    repo_gpgcheck: true
    # boourns
    gpgcheck: false
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg
  when: ansible_facts["distribution"] == "Fedora"
  tags:
    - tailscale

- name: Install Tailscale
  become: true
  ansible.builtin.package:
    name: tailscale
    state: present
  tags:
    - packages
    - tailscale
