---
- name: Add Tailscale repo key
  become: true
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_facts["distribution_release"] }}.gpg
  when: ansible_facts["distribution"] == "Ubuntu"
  tags:
    - tailscale

- name: Add Tailscale repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu {{ ansible_facts["distribution_release"] }} main
    state: present
    filename: keybase
  when: ansible_facts["distribution"] == "Ubuntu"
  tags:
    - tailscale

- name: Add Tailscale repo
  become: true
  ansible.builtin.yum_repository:
    name: tailscale
    description: Tailscale
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    enabled: true
    repo_gpgcheck: true
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg
  when: ansible_facts["distribution"] == "Fedora"
  tags:
    - tailscale

- name: Install Tailscale
  become: true
  ansible.builtin.package:
    name: tailscale
    state: present
  tags:
    - packages
    - tailscale
