---

- name: Install Flatpak
  become: true
  package:
    name: flatpak
    state: present
  when: ansible_facts["os_family"] != "Darwin"
  tags:
  - flatpak
  - packages

- name: Add Flathub remote
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
  - flatpak
