---
- name: Install asdf version manager
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    version: v0.10.2
    dest: "{{ home }}/.asdf"
    update: true
  tags:
    - asdf
    - development_workstation

- name: Install plugins for asdf
  ansible.builtin.command: "{{ home }}/.asdf/bin/asdf plugin-add {{ item }}"
  args:
    creates: "{{ home }}/.asdf/plugins/{{ item }}"
  with_items:
    - erlang
    - elixir
    - ruby
    - nodejs
    - kubectl
    - helm
    - terraform
    - golang
    - maven
    - hugo
  tags:
    - asdf
    - development_workstation
