---

- name: Install Azure CLI
  become: yes
  package:
    name: azure-cli
    state: present
  when: ansible_facts["os_family"] != "Darwin"
  tags:
  - azure
  - packages

- name: Install Azure CLI
  homebrew:
    name: azure-cli
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
  - azure
  - packages
