---

- name: Clone dotfiles
  git:
    repo: https://github.com/alexblackie/dotfiles.git
    dest: "{{ home }}/.dotfiles"
    accept_hostkey: yes
    update: no
  tags:
  - dotfiles

- name: Install dotfiles
  shell: FORCE=1 ./install
  args:
    chdir: "{{ home }}/.dotfiles"
    creates: "{{ home }}/.commonrc"
  tags:
  - dotfiles
