---

- name: Install JDK
  dnf:
    name:
      - java-latest-openjdk
      - java-latest-openjdk-devel
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - packages
  - java

- name: Install JDK
  apt:
    name: default-jdk
    state: present
  become: yes
  when: ansible_facts["distribution"] == "Ubuntu"
  tags:
  - packages
  - java
