---

- name: Install JDK
  become: true
  package:
    name:
    - java-16-openjdk
    - java-16-openjdk-devel
    state: present
  when: ansible_facts["os_family"] == "Suse"
  tags:
  - packages
  - java
