---
- name: Install JDK
  ansible.builtin.dnf:
    name:
      - java-latest-openjdk
      - java-latest-openjdk-devel
    state: present
  become: true
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - packages
    - java

- name: Install JDK
  ansible.builtin.apt:
    name: default-jdk
    state: present
  become: true
  when: ansible_facts["os_family"] == "Debian"
  tags:
    - packages
    - java
