---

- name: Install JDK
  become: true
  dnf:
    name:
      - java-latest-openjdk
      - java-latest-openjdk-devel
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - packages
  - java

- name: Install JDK
  homebrew_cask:
    name: oracle-jdk
    state: present
  when: ansible_facts["os_family"] == "Darwin"
  tags:
  - packages
  - java
