---
- name: Ensure neovim dependencies are installed
  become: true
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present
  when: ansible_facts["os_family"] == "Debian"

- name: Clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ third_party_src }}/neovim"
    version: stable
    update: true
    force: true
  when: ansible_facts["os_family"] == "Debian"

- name: Compile and install neovim
  ansible.builtin.command: make install CMAKE_INSTALL_PREFIX={{ home }}/.local CMAKE_BUILD_TYPE=RelWithDebInfo
  args:
    chdir: "{{ third_party_src }}/neovim"
    creates: "{{ home }}/.local/bin/nvim"
  when: ansible_facts["os_family"] == "Debian"
