---
- name: Ensure neovim dependencies are installed
  become: "{{ elevate_for_package_installation }}"
  ansible.builtin.package:
    name: "{{ neovim_dependencies }}"
    state: present
  tags:
    - packages
    - neovim

- name: Clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ third_party_src }}/neovim"
    version: stable
    update: true
    force: true
  tags:
    - neovim

- name: Compile and install neovim
  ansible.builtin.command: make install CMAKE_INSTALL_PREFIX={{ home }}/.local CMAKE_BUILD_TYPE=RelWithDebInfo
  args:
    chdir: "{{ third_party_src }}/neovim"
    creates: "{{ home }}/.local/bin/nvim"
  tags:
    - neovim

- name: Install the Elixir language server manually
  tags:
    - neovim
    - lsp
  block:
    - name: Clone elixir-ls
      ansible.builtin.git:
        repo: https://github.com/elixir-lsp/elixir-ls.git
        dest: "{{ third_party_src }}/elixir-ls"
        update: true
        force: true

    # We won't have elixir installed yet, so we just dump the commands into a
    # script to at least make it easier for manual execution later.
    - name: Add build script
      ansible.builtin.copy:
        content: "mix deps.get && mix compile && mix elixir_ls.release -o release"
        dest: "{{ third_party_src }}/elixir-ls/build.sh"
        mode: "0755"
