---
- name: Install tools for RPM development
  become: "{{ elevate_for_package_installation }}"
  ansible.builtin.package:
    name:
      - redhat-rpm-config
      - rpm-build
      - pkgconfig
  when: ansible_facts["os_family"] == "RedHat"
