---

- name: Install redis
  become: true
  package:
    name: redis
    state: present
  when: ansible_facts["os_family"] == "Suse"

- name: Install redis
  homebrew:
    name: redis
    state: present
  when: ansible_facts["os_family"] == "Darwin"
