---

- name: Install redis
  dnf:
    name: redis
    state: present
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Install redis
  apt:
    name: redis-server
    state: present
  become: yes
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install redis
  homebrew:
    name: redis
    state: present
  when: ansible_facts["os_family"] == "Darwin"
