---
- name: Install redis
  become: true
  ansible.builtin.dnf:
    name: redis
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install redis
  become: true
  ansible.builtin.apt:
    name: redis-server
    state: present
  when: ansible_facts["os_family"] == "Debian"
