---

- name: Install redis
  become: true
  dnf:
    name: redis
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install redis
  homebrew:
    name: redis
    state: present
  when: ansible_facts["os_family"] == "Darwin"
