---

- name: Install redis
  become: true
  dnf:
    name: redis
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install redis
  become: true
  apt:
    name: redis-server
    state: present
  when: ansible_facts["os_family"] == "Debian"
