---
- name: Add rtx yum repository
  become: true
  ansible.builtin.yum_repository:
    name: rtx
    description: rtx
    baseurl: https://rtx.pub/rpm
    enabled: true
    gpgcheck: true
    gpgkey: http://rtx.pub/gpg-key.pub
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - rtx

- name: Add rtx apt repository
  become: true
  when: ansible_facts["os_family"] == "Debian"
  tags:
    - rtx
  block:
    - name: Fetch rtx repo signing key
      ansible.builtin.get_url:
        url: https://rtx.pub/gpg-key.pub
        dest: /etc/apt/trusted.gpg.d/rtx.asc
        checksum: sha256:bf3bedf8b33a9486ba1a2f488b3fc59c6080b7a06fb7e5d3deac3ffa6aaaf2e2
        mode: "0644"

    - name: Add rtx apt repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/rtx.asc arch={{ ansible_architecture }}] https://rtx.pub/deb stable main
        state: present

- name: Install rtx via Homebrew
  when: ansible_facts["os_family"] == "Darwin"
  tags:
    - rtx
  block:
    - name: Add rtx Homebrew tap
      community.general.homebrew_tap:
        name: jdxcode/tap
        state: present

- name: Install rtx
  become: true
  ansible.builtin.package:
    name: "{{ rtx_package }}"
    state: present
  tags:
    - rtx

- name: Install plugins for rtx
  ansible.builtin.command: rtx plugins install {{ item }}
  args:
    creates: "{{ home }}/.local/share/rtx/plugins/{{ item }}"
  with_items:
    - erlang
    - elixir
    - ruby
    - nodejs
    - kubectl
    - terraform
    - golang
    - maven
    - hugo
    - rust
  tags:
    - rtx
