---
# We need to `become` for package installs on Linux, but not on macOS, so we
# "become" ourselves to treat it as a no-op.
become_user: "{{ user }}"

development_packages:
  - autoconf
  - entr
  - findutils
  - gnupg
  - htop
  - imagemagick
  - jq
  - nmap
  - optipng
  - pwgen
  - shellcheck
  - sqlite
  - ripgrep
  - tmux
  - wget
  - wxmac
  - postgresql
  - rclone
  - exa
  - gawk

fd_package: fd

java_package: openjdk@17

neovim_dependencies:
  - ninja
  - libtool
  - cmake
  - pkg-config
  - gettext

python_packages:
  - python3
