---

- name: Install QEMU and libvirt
  become: true
  package:
    name:
    - qemu-kvm
    - libvirtd
    state: present
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - virt
  - packages

- name: Enable and start libvirtd
  become: true
  service:
    name: libvirtd
    state: started
    enabled: yes
  when: ansible_facts["os_family"] == "RedHat"
  tags:
  - virt
