---

# Since ansible_user_id will be `root` if we `become: yes`, this caches the
# unprivileged user in a fact for us to use everywhere.
- name: Get local username
  set_fact:
    local_user: "{{ ansible_user_id }}"

- name: Get home directory path
  set_fact:
    home: "{{ lookup('env', 'HOME') }}"

- name: Enable fastest mirror dnf plugin
  become: yes
  lineinfile:
    line: fastestmirror=1
    dest: /etc/dnf/dnf.conf
  when: ansible_facts["os_family"] == "RedHat"

- name: Enable RPMFusion free
  become: yes
  dnf:
    name:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts["distribution_major_version"] }}.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts["distribution_major_version"] }}.noarch.rpm
    disable_gpg_check: true
    state: present
  when: ansible_facts["distribution"] == "Fedora"

- name: Install base system software
  become: true
  apt:
    name:
      - openssh-server
      - gnupg
      - apt-transport-https
    state: present
  when: ansible_facts["os_family"] == "Debian"

- name: Enable sshd
  service:
    name: sshd
    state: started
    enabled: yes
  become: yes
  when: ansible_facts["os_family"] == "RedHat"

- name: Enable ssh
  service:
    name: ssh
    state: started
    enabled: yes
  become: yes
  when: ansible_facts["os_family"] == "Debian"

- name: Install fwupd for firmware update support
  become: yes
  dnf:
    name: fwupd
    state: present
  when: ansible_facts["os_family"] == "RedHat"
