---
- name: Add Azure CLI Yum repository
  become: true
  ansible.builtin.yum_repository:
    name: azure-cli
    description: Azure CLI
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - azure
    - packages

- name: Add Microsoft signing key
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
    mode: "0644"
  when: ansible_facts["os_family"] == "Debian"
  tags:
    - azure
    - packages

- name: Add Azure CLI repository
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/etc/apt/trusted.gpg.d/microsoft.asc]
      https://packages.microsoft.com/repos/azure-cli/
      {{ ansible_facts["distribution_release"] }} main
    state: present
  when: ansible_facts["os_family"] == "Debian"
  tags:
    - azure
    - packages

- name: Install Azure CLI
  become: "{{ elevate_for_package_installation }}"
  ansible.builtin.package:
    name: azure-cli
    state: present
  tags:
    - azure
    - packages
