---
- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/alexblackie/dotfiles.git
    dest: "{{ home }}/.dotfiles"
    accept_hostkey: true
    update: false
  tags:
    - dotfiles

- name: Install dotfiles
  ansible.builtin.command: ./install
  args:
    chdir: "{{ home }}/.dotfiles"
    creates: "{{ home }}/.commonrc"
  tags:
    - dotfiles
